# -*- coding: utf-8 -*-
"""Seq2SeqDecoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aA5Jc5CWO6Zxw6FIheO9Bcmj1lT-_B8N
"""

! pip install torch_geometric

import json
import torch
import torch.nn as nn
from torch.utils.data import Dataset, random_split
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader as GNNDataLoader
from torch.optim.lr_scheduler import CosineAnnealingLR
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt
import numpy as np
import os

# --- 1. CONFIGURATION ---
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
EPOCHS = 100
BATCH_SIZE = 16
PATIENCE = 10  # For Early Stopping
LR = 1e-4

# --- 2. DATASET & DATA PREP ---
class HybridSymbolicDataset(Dataset):
    def __init__(self, embedding_path, label_path):
        with open(embedding_path, "r") as f:
            self.embeddings = [torch.tensor(e["embedding"], dtype=torch.float32) for e in json.load(f)]
        with open(label_path, "r") as f:
            data = json.load(f)
            self.token_seqs = data["tokenized_trees"]
            self.vocab = data["vocab"]
            self.inv_vocab = {v: k for k, v in self.vocab.items()}

        self.pad_id = self.vocab.get("<PAD>", max(self.vocab.values()) + 1)
        self.eos_id = self.vocab.get("<EOS>", max(self.vocab.values()) + 2)
        self.sos_id = len(self.vocab) + 2
        self.max_len = max(len(seq) for seq in self.token_seqs) + 2

    def __len__(self): return len(self.embeddings)

    def __getitem__(self, idx):
        emb = self.embeddings[idx]
        tokens = [self.sos_id] + self.token_seqs[idx] + [self.eos_id]
        padded = tokens + [self.pad_id] * (self.max_len - len(tokens))

        # Skeleton Graph (Binary structure)
        edge_index = torch.tensor([[0, 1], [0, 2]], dtype=torch.long)
        node_feats = torch.eye(len(self.vocab) + 5)[tokens[:3]]

        return {
            "embedding": emb,
            "graph": Data(x=node_feats, edge_index=edge_index),
            "target_ids": torch.tensor(padded, dtype=torch.long)
        }

# Initialize Data
full_dataset = HybridSymbolicDataset("/content/tnet_embeddings.json", "/content/tokenized_gpt_labels_with_full_funcs.json")
train_size = int(0.8 * len(full_dataset))
val_size = len(full_dataset) - train_size
train_ds, val_ds = random_split(full_dataset, [train_size, val_size])

train_loader = GNNDataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
val_loader = GNNDataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False)

# --- 3. SPARSE ATTENTION MODULE ---
class SparseAttention(nn.Module):
    def __init__(self, embed_dim, num_heads, window_size=8, num_random=4):
        super().__init__()
        self.attn = nn.MultiheadAttention(embed_dim, num_heads, batch_first=True)
        self.window_size = window_size
        self.num_random = num_random

    def forward(self, x):
        B, T, D = x.shape
        mask = torch.full((T, T), float("-inf"), device=x.device)
        for i in range(T):
            # Window Attention
            start = max(0, i - self.window_size)
            mask[i, start:i+1] = 0
            # Random Attention (Global sparse connectivity)
            if self.num_random > 0:
                rand_idx = torch.randint(0, T, (self.num_random,), device=x.device)
                mask[i, rand_idx] = 0
        attn_out, _ = self.attn(x, x, x, attn_mask=mask)
        return attn_out

# --- 4. MODIFIED HYBRID MODEL (GNN Encoder + Sparse Transformer Decoder) ---
class NextGenSymbolicModel(nn.Module):
    def __init__(self, vocab_size, tnet_dim=128, gpt_dim=256, n_layers=3, n_heads=4):
        super().__init__()
        # GNN Structural Encoder
        self.gnn = nn.Sequential(
            nn.Linear(vocab_size + 5, 128),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(128, 128)
        )

        # Multimodal Fusion & Embedding
        self.fusion = nn.Linear(tnet_dim + 128, gpt_dim)
        self.token_emb = nn.Embedding(vocab_size + 5, gpt_dim)
        self.pos_emb = nn.Parameter(torch.randn(1, 250, gpt_dim))
        self.dropout = nn.Dropout(0.3)

        # Sparse Transformer Decoder Layers
        self.layers = nn.ModuleList([
            nn.ModuleDict({
                "sparse_attn": SparseAttention(gpt_dim, n_heads),
                "ff": nn.Sequential(
                    nn.Linear(gpt_dim, 4 * gpt_dim),
                    nn.ReLU(),
                    nn.Dropout(0.15),
                    nn.Linear(4 * gpt_dim, gpt_dim)
                ),
                "norm1": nn.LayerNorm(gpt_dim),
                "norm2": nn.LayerNorm(gpt_dim),
            }) for _ in range(n_layers)
        ])

        self.head = nn.Linear(gpt_dim, vocab_size + 5)

    def forward(self, tnet_emb, graph_batch, target_ids):
        # 1. Structural Context from GNN
        struct_feats = self.gnn(graph_batch.x)
        # Global pooling across the batch
        struct_ctx = struct_feats.mean(dim=0).repeat(tnet_emb.size(0), 1)

        # 2. Multimodal Fusion (T-Net Data + GNN Structure)
        # We project the concatenated latent space into the GPT dimension
        fused_context = self.fusion(torch.cat([tnet_emb, struct_ctx], dim=-1)).unsqueeze(1)

        # 3. Target Sequence Embedding
        B, T = target_ids.shape
        tok_embed = self.dropout(self.token_emb(target_ids))

        # Concatenate fused context as a 'prefix' token
        x = torch.cat([fused_context, tok_embed], dim=1)
        x = x + self.pos_emb[:, :T+1, :]

        # 4. Sparse Decoding Layers
        for layer in self.layers:
            attn_out = layer["sparse_attn"](x)
            x = layer["norm1"](x + attn_out)
            ff_out = layer["ff"](x)
            x = layer["norm2"](x + ff_out)

        # Slice out the prefix token to get logits for the sequence
        logits = self.head(x[:, 1:, :])
        return logits

## --- 4. TRAINING WITH VALIDATION & EARLY STOPPING ---
# Ensure NextGenSymbolicModel is initialized with the SparseAttention layers
# as defined in our previous block.
model = NextGenSymbolicModel(
    vocab_size=len(full_dataset.vocab),
    tnet_dim=128,
    gpt_dim=128,      # Reduced to 128 for better generalization
    n_layers=4        # Slimmer model to prevent overfitting
).to(device)

# Regularization-heavy optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4, weight_decay=1e-3)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3)
# Label smoothing helps the Sparse Attention not over-focus on specific tokens
criterion = nn.CrossEntropyLoss(ignore_index=full_dataset.pad_id, label_smoothing=0.1)

train_losses, val_losses = [], []
best_val_loss = float('inf')
early_stop_counter = 0

for epoch in range(EPOCHS):
    # --- Training Phase ---
    model.train()
    t_loss = 0
    for batch in tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS}"):
        emb, graph, tgt = batch["embedding"].to(device), batch["graph"].to(device), batch["target_ids"].to(device)

        # Multimodal Augmentation: Add 1% Gaussian noise to PointNet embeddings
        if model.training:
            noise_factor = 0.01 * (1 - (epoch / EPOCHS))
            emb = emb + torch.randn_like(emb) * noise_factor

        # Forward pass: Predicting the skeleton
        logits = model(emb, graph, tgt[:, :-1])
        loss = criterion(logits.reshape(-1, logits.size(-1)), tgt[:, 1:].reshape(-1))

        optimizer.zero_grad()
        loss.backward()
        # Gradient clipping to stabilize sparse attention training
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        t_loss += loss.item()

    # --- Validation Phase ---
    model.eval()
    v_loss = 0
    with torch.no_grad():
        for batch in val_loader:
            emb, graph, tgt = batch["embedding"].to(device), batch["graph"].to(device), batch["target_ids"].to(device)
            # No noise during validation
            logits = model(emb, graph, tgt[:, :-1])
            v_loss += criterion(logits.reshape(-1, logits.size(-1)), tgt[:, 1:].reshape(-1)).item()

    avg_t, avg_v = t_loss / len(train_loader), v_loss / len(val_loader)
    train_losses.append(avg_t)
    scheduler.step(avg_v)
    val_losses.append(avg_v)

    print(f"Loss -> Train: {avg_t:.4f} | Val: {avg_v:.4f} | LR: {scheduler.get_last_lr()[0]:.6f}")

    # --- Checkpointing & Early Stopping ---
    if avg_v < best_val_loss:
        best_val_loss = avg_v
        early_stop_counter = 0
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': best_val_loss,
            'vocab': full_dataset.vocab,
        }, "best_sparse_hybrid_model.pth")
    else:
        early_stop_counter += 1
        if early_stop_counter >= PATIENCE:
            print(f"✅ Early stopping triggered at Epoch {epoch+1}. Model generalized.")
            break

# Final Learning Curve Plot
plt.figure(figsize=(10, 5))
plt.plot(train_losses, label="Train Loss (Augmented)")
plt.plot(val_losses, label="Validation Loss (Generalization)")
plt.xlabel("Epochs")
plt.ylabel("Cross Entropy Loss")
plt.title("Stability Analysis: Sparse GNN-Transformer")
plt.legend()
plt.grid(True)
plt.show()

import json

def generate_predictions_file(model, dataset, save_path="predictions.json"):
    model.eval()
    predictions = []

    # Use the full dataset or validation dataset to see how well it recovered
    print(f"Generating predictions for {len(dataset)} samples...")

    with torch.no_grad():
        for i in tqdm(range(len(dataset)), desc="Inference"):
            data = dataset[i]
            # Prep inputs (add batch dimension)
            emb = data["embedding"].unsqueeze(0).to(device)
            graph = data["graph"].to(device)

            # Start with the SOS token
            input_ids = torch.tensor([[dataset.sos_id]], device=device)

            # Autoregressive generation
            for _ in range(dataset.max_len):
                logits = model(emb, graph, input_ids)
                # Get the last predicted token
                next_token = logits[:, -1, :].argmax(dim=-1).unsqueeze(0)
                input_ids = torch.cat([input_ids, next_token], dim=1)

                # Stop if EOS is reached
                if next_token.item() == dataset.eos_id:
                    break

            # Convert token IDs to Symbols
            # Filter out SOS, EOS, and PAD for the final output string
            pred_tokens = [
                dataset.inv_vocab.get(t.item(), "const(C)")
                for t in input_ids.squeeze()
                if t.item() not in [dataset.sos_id, dataset.eos_id, dataset.pad_id]
            ]

            # Get Ground Truth for comparison
            true_tokens = [
                dataset.inv_vocab.get(t, "const(C)")
                for t in dataset.token_seqs[i]
            ]

            predictions.append({
                "id": i,
                "predicted_skeleton": " ".join(pred_tokens),
                "ground_truth": " ".join(true_tokens)
            })

    with open(save_path, "w") as f:
        json.dump(predictions, f, indent=4)

    print(f"predictions.json created with {len(predictions)} entries.")


generate_predictions_file(model, full_dataset)

import json

def generate_gp_seeds(model, dataset, num_samples=100):
    model.eval()
    gp_seeds = []

    print(f"Generating {num_samples} GP seeds...")

    with torch.no_grad():
        for i in range(min(num_samples, len(dataset))):
            data = dataset[i]
            emb = data["embedding"].unsqueeze(0).to(device)
            graph = data["graph"].to(device)

            # Start the sequence with the SOS token
            input_ids = torch.tensor([[dataset.sos_id]], device=device)

            # Greedy decoding to build the skeleton
            for _ in range(dataset.max_len):
                logits = model(emb, graph, input_ids)
                # Get the most likely next token
                next_token = logits[:, -1, :].argmax(dim=-1).unsqueeze(0)
                input_ids = torch.cat([input_ids, next_token], dim=1)

                # Stop if we hit the EOS token
                if next_token.item() == dataset.eos_id:
                    break

            # Convert token IDs back to actual math symbols from your vocab
            # We skip SOS, EOS, and PAD to get a clean skeleton
            skeleton_tokens = [
                dataset.inv_vocab.get(t.item(), "const(C)")
                for t in input_ids.squeeze()
                if t.item() not in [dataset.sos_id, dataset.eos_id, dataset.pad_id]
            ]

            gp_seeds.append({
                "sample_id": i,
                "skeleton": " ".join(skeleton_tokens)
            })

    # Save to the json file
    save_path = "gp_seeds.json"
    with open(save_path, "w") as f:
        json.dump(gp_seeds, f, indent=4)

    return save_path

# Execute the generation
file_path = generate_gp_seeds(model, full_dataset)
print(f"Success! Your seeds are ready at: {file_path}")

