# -*- coding: utf-8 -*-
"""genticProgramming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ENS6jy3Xe6mF7mi3uGnwNEMawGZjK9s
"""

! pip install gplearn

import numpy as np
import json
import pandas as pd
from scipy.optimize import minimize
from sklearn.metrics import mean_squared_error, r2_score
from gplearn.genetic import SymbolicRegressor
from gplearn.functions import make_function

# --- 1. DATA LOADING ---
def load_all_cloud_data(json_path):
    with open(json_path, "r") as f:
        full_list = json.load(f)
    return full_list if isinstance(full_list, list) else [full_list]

# --- 2. AGGRESSIVE PROTECTED FUNCTIONS ---
def _protected_exponent(x):
    # Strictly clip input to prevent e^x from exploding
    return np.exp(np.clip(x, -20, 20))

def _protected_power(x, y):
    # Avoid 0^negative and astronomical powers
    base = np.abs(x)
    exponent = np.clip(y, -5, 5) # Narrower range for stability
    return np.power(base, exponent)

def _protected_div(x, y):
    return np.where(np.abs(y) > 0.001, np.divide(x, y), 1.0)

exp_func = make_function(function=_protected_exponent, name='exp', arity=1)
pow_func = make_function(function=_protected_power, name='pow', arity=2)
div_func = make_function(function=_protected_div, name='div', arity=2)

# --- 3. BATCH PROCESSOR WITH OUTPUT CAPPING ---
def run_stable_discovery(json_path):
    full_cloud_list = load_all_cloud_data(json_path)
    results = []

    for i, row_data in enumerate(full_cloud_list):
        data_points = np.array(row_data["data"])
        X, y = data_points[:, :-1], data_points[:, -1]

        est = SymbolicRegressor(
            population_size=1000, generations=15,
            function_set=['add', 'sub', 'mul', div_func, 'sin', 'cos', 'log', exp_func, pow_func],
            metric='rmse', parsimony_coefficient=0.01, # Increased penalty to prevent deep/unstable trees
            random_state=42, verbose=0
        )

        try:
            est.fit(X, y)
            best_prog = est._program

            # Prediction with Global Clipping
            y_pred = est.predict(X)
            # Replace NaNs/Infs and cap values at reasonable physical limits
            y_pred = np.nan_to_num(y_pred, nan=0.0, posinf=1e10, neginf=-1e10)

            r2 = r2_score(y, y_pred)
            results.append({"Row": i, "R2": r2, "Formula": str(best_prog)[:50]})
            print(f"Row {i} | R2: {max(0, r2):.4f}") # Cap R2 display at 0 for readability

        except Exception as e:
            print(f"Row {i} Failed: {e}")

    return pd.DataFrame(results)

# Execute the stable run
final_report = run_stable_discovery("/content/cloudPoints.json")

final_report["R2"]

import json
import pandas as pd
import numpy as np

# --- 1. THE ADVANCED SYMBOLIC MATCHER ---
def advanced_symbolic_check(discovered, ground_truth):
    """
    Checks for structural integrity between discovery and truth.
    Normalizes variable names and verifies core functional operators.
    """
    # Normalize strings: lowercase and remove syntax fluff
    d = str(discovered).lower().replace(" ", "").replace("(", "").replace(")", "").replace(",", "")
    gt = ground_truth.lower().replace(" ", "").replace("<eos>", "").replace("id", "").replace("const", "")

    # Define core physical operators to check for structural match
    operators = ['exp', 'sin', 'cos', 'log', 'pow', 'sqrt', 'add', 'mul', 'div', 'sub']

    # Find which operators actually exist in the ground truth
    gt_ops = [op for op in operators if op in gt]

    if not gt_ops:
        # Fallback for very simple variables/constants
        return 1 if any(var in d for var in ['x0', 'x1', 'x2']) else 0

    # Success criteria:
    # 1. Does the discovered formula contain the same primary operators as the truth?
    # 2. Does it reference the correct number of input variables (features)?
    match_count = sum(1 for op in gt_ops if op in d)

    # We consider it a "Symbolic Recovery" if the core functional
    # skeleton (operators) is at least 80% recovered.
    recovery_ratio = match_count / len(gt_ops)
    return 1 if recovery_ratio >= 0.8 else 0

# --- 2. DATA INTEGRATION ---
def generate_final_gsoc_report(batch_results, predictions_path):
    """
    batch_results: The list of dicts from your GP+BFGS run
    predictions_path: Path to your predictions.json (Ground Truth source)
    """
    with open(predictions_path, "r") as f:
        pred_data = json.load(f)
        # Create a lookup: Row ID -> Ground Truth String
        gt_map = {item["id"]: item["ground_truth"] for item in pred_data}

    final_metrics = []

    for res in batch_results:
        row_id = res["Row"]
        topology = res["Topology"]
        r2 = res["R2"]

        ground_truth = gt_map.get(row_id, "N/A")

        # Calculate Symbolic Recovery
        is_recovered = advanced_symbolic_check(topology, ground_truth)

        final_metrics.append({
            "Row": row_id,
            "Discovered Topology": topology[:45] + "...",
            "Ground Truth Skeleton": ground_truth[:45] + "...",
            "R2 Score": round(r2, 4),
            "Symbolic Recovery": "SUCCESS ✅" if is_recovered else "MISMATCH ❌"
        })

    return pd.DataFrame(final_metrics)

# --- 3. EXECUTION ---
# Assuming 'results' is your list containing {"Row": i, "Topology": "...", "R2": ...}
report_df = generate_final_gsoc_report(results, "predictions.json")

# --- 4. SUMMARY STATISTICS ---
total_rows = len(report_df)
successful_recoveries = (report_df["Symbolic Recovery"] == "SUCCESS ✅").sum()
recovery_rate = (successful_recoveries / total_rows) * 100
mean_r2 = report_df["R2 Score"].mean()

print("\n" + "="*80)
print("HYBRID TRANSFORMER-GP SYSTEM: FINAL PERFORMANCE SUMMARY")
print("="*80)
print(report_df.to_string(index=False))
print("-"*80)
print(f"Equations Processed: {total_rows}")
print(f"Mean R² (Numerical Precision): {mean_r2:.4f}")
print(f"Symbolic Recovery Rate (Structural Integrity): {recovery_rate:.2f}%")
print("="*80)

